### ISSUE TITLE
No Wifi connection

### ISSUE THREAD

**Issue by trumpel1** [tobiasfaust/SolaxModbusGateway#10]
Hi Tobias,

i tried to setup the ESP32 by flashing the firmware.bin.
Am I doing sth wrong here? I'm new and not sure how to start other than flashing the firmware.bin.
From the wiki I could not assume sth other than doing that step.
Normally I use Arduino for small scripts which I flash so GPIO is no issue.

Thank you!

![firmware](https://user-images.githubusercontent.com/125611754/219498001-0c2114c9-072d-428b-9625-6ba0c464c575.PNG)

Viele Grüße
Toni

**Comment by tobiasfaust** [comment]
Hi Toni,
please follow the instructions in my wiki:
https://github.com/tobiasfaust/SolaxModbusGateway/wiki/build-with-gitpod
https://github.com/tobiasfaust/SolaxModbusGateway/wiki/start-and-integration-into-locale-wifi
