### ISSUE TITLE
OTA Update mit Custom Firmware

### ISSUE THREAD

**Issue by Lazgar** [tobiasfaust/SolaxModbusGateway#104]
Hey Tobias,

Bei mir funktioniert in der neuesten Version ein Update mit einer Custom Firmware nicht mehr.

LG Lazgar

**Comment by tobiasfaust** [comment]
erledigt in der aktuellen Dev [f7cabf5](https://github.com/tobiasfaust/SolaxModbusGateway/commit/f7cabf54f098c4a1451715077157f800476e91a5) , hat sich leider ein dummer Fehler eingeschlichen
