### ISSUE TITLE
Fix a missleading entry in the Wiki please for Board HW-97

### ISSUE THREAD

**Issue by UdoD5** [tobiasfaust/SolaxModbusGateway#11]
Hi, 
you might want to update the description in the wiki for the Board HW-97. In the description you are mentioning that DI and RO need to be connected together but actually it is DE and RE (like in the schematics). Another point is that the RTS Pin should be DI5 according to the schematics but in the firmware the default setting is D18. 
Unfortunatly I can't get it to work. Flashed the firmware on the ESP but no values from the Solax are showing up. I replaced the cable the ESB and the HW-97 Board.  I'll give it a try with another RS485 Converter Board the next days..

**Comment by UdoD5** [comment]
Unfortunatly also with the Board SP3485 no luck. As soon as I connect the RST Pin I can't connect to the ESP32, Wlan seems to be gone (I switched bettween PIN 5 and 18 both times the same result). With RST connected the ESP32 does not boot.

**Comment by tobiasfaust** [comment]
HI,
the connection table is, in my opinion, correct:
https://github.com/tobiasfaust/SolaxModbusGateway/wiki/wiring-the-circuit#esp--breakout-board

please note: RST is not RTS!
