### ISSUE TITLE
autoconenct wifi after router reboot

### ISSUE THREAD

**Issue by Coolj1** [tobiasfaust/SolaxModbusGateway#21]
hi tobias,
this software works great, except for the case when i reboot my router, the wifi doesn't reconnect automatically... is there a solution?

thanks a lot
Mit freundlichen Grüßen
Hans

**Comment by DJFS** [comment]
Hallo,

ich habe leider das Problem das sich irgendwas immer aufhängt und ich manchmal 2mal täglich, selten mal alle 2 Tage des ESP32 Neu starten muss. :( .

**Comment by tobiasfaust** [comment]
Hi @Coolj1 
Can you confirm the fix?

**Comment by kommando828** [comment]
I have been getting the same issue and never got more than 36 hours before a reboot was needed for it reappear on the network, loaded the new code and its at 16 hrs uptime. Will update in 2 days.

**Comment by DJFS** [comment]
Gibt es hierzu ein neues Update?

**Comment by kommando828** [comment]
> Is there a new update for this?

https://github.com/tobiasfaust/SolaxModbusGateway/commit/dc3243aef3d89f5c2d4f1d8197dbf8c04f7946ad

**Comment by tobiasfaust** [comment]
That commit makes the esp more robust and fixes the automatic reconnect to wifi if wifi was broken suddenly

**Comment by DJFS** [comment]
Wo ist dieser Update datei? 
![image](https://github.com/tobiasfaust/SolaxModbusGateway/assets/134227035/c0887231-a08e-4662-a66f-8e2597534893)

**Comment by Coolj1** [comment]
hallo Tobias,
in der Version 3.11 funktioniert oben in der Config der Link Item Config nicht mehr, und es werden auch keine Einheiten mehr hinter den Werten in LiveData angezeigt.

autoconnect wifi scheint zu funtionieren!


danke
Gruß Hans

**Comment by DJFS** [comment]
@cool1 , wie hast du denn das update gemacht?

**Comment by Coolj1** [comment]
@tobiasfaust , compiliert und dann mit der Update-Funktion die firmware.bin hochgeladen

**Comment by tobiasfaust** [comment]
> @tobiasfaust , compiliert und dann mit der Update-Funktion die firmware.bin hochgeladen. ich hab auch einen anderen Esp32 direkt über PlatformIO programmiert, der zeigt das gleiche Phänomen.
> 
> o.k. hab gerade herausgefunden, wenn ich auf den Inverter Solax-X3 umschalte, komme ich nicht mehr auf die item config Seite!

Fehler gefunden, dauert aber ein paar Tage die Lösung zu finden. Es gibt bei großen Register 
Definitionen einen Speicherüberlauf und der ESP rebootet.

**Comment by kommando828** [comment]
If you change to the X3 the Uptime counter also clears back to Zero which fits in with a memory overflow, changing back to MIC and the counter does not clear.

**Comment by kommando828** [comment]
Went to move the ESP32 after 3 days success of stable Wifi and reset Wifi before going outside to reconnect to the outside AP near to inverter. AP_Solax now requires a password instead of going straight to setup page, default password 123456789 is not working.

**Comment by tobiasfaust** [comment]
Sorry,
Password is 

MbMQTTGtw

i have to insert this in Wiki asap….

**Comment by kommando828** [comment]
Thanks, that works ;)

In middle of downpour so when it stops I will go back outside and check the Modbus is still working with the X1 Boost version of MIC.

**Comment by kommando828** [comment]
Test confirms Modbus is still working for X1-boost using truncated MIC poll.

**Comment by tobiasfaust** [comment]
> @tobiasfaust , compiliert und dann mit der Update-Funktion die firmware.bin hochgeladen. ich hab auch einen anderen Esp32 direkt über PlatformIO programmiert, der zeigt das gleiche Phänomen.
> 
> o.k. hab gerade herausgefunden, wenn ich auf den Inverter Solax-X3 umschalte, komme ich nicht mehr auf die item config Seite!

get in #22 weiter
