### ISSUE TITLE
Seit neuem Update keine OpenWB Daten mehr bei X3 Hybrid

### ISSUE THREAD

**Issue by MagicSven81** [tobiasfaust/SolaxModbusGateway#22]
Ich bekomme bei Auswahl des X3 Hybrid WR keine Möglichkeit mehr OpenWB Daten zu markieren.
Stelle ich auf X1 Hybrid oder MIC um, sind diese wieder zu sehen.
Bitte einmal prüfen - Danke.

![image](https://github.com/tobiasfaust/SolaxModbusGateway/assets/41968180/e4b7674b-2791-44b0-a17e-3bf4b076e6bc)

**Comment by tobiasfaust** [comment]
Ist hier schon berichtet worden #21 
Ist leider ein Speicherüberlauf der etwas dauert zu beseitigen.
Als workaround bis dahin hilft es in der Register.h die Anzahl der Items für den X3 zu reduzieren

**Comment by tobiasfaust** [comment]
schneller Fix mit e8cdade um den Absturz des ESP wegen Speicherüberlaufes zu verhindern.
Aber Achtung: Die Infos ob ein Item OpenWB fähig ist oder nicht (spalte OpenWB) wird noch nicht angezeigt, kommt später

**Comment by tobiasfaust** [comment]
> Ok danke, wie entferne ich unnötige Items aus der register.h ? Auf was muss ich da achten?

Mit dem letzten commit nicht mehr notwendig

**Comment by DJFS** [comment]
Heute hab ich ein Update gemacht. Nun geht nach einmal MQTT Übertragung immer gar nichts mehr :(

**Comment by tobiasfaust** [comment]
Ich Check das Montag, 
Kann ich mir nicht wirklich erklären da ich ausschließlich an der Web-Ausgabe gearbeitet hatte

Bitte noch mehr Details: gibt es Probleme nur beim X3? 
Wann hört MQTT auf?

**Comment by tobiasfaust** [comment]
> Heute hab ich ein Update gemacht. Nun geht nach einmal MQTT Übertragung immer gar nichts mehr :(

getestet, kann ich nicht nachvollziehen, MQTT messages der aktiverten Items werden kontinuierlich übertragen

**Comment by tobiasfaust** [comment]
finally fixed with 6adb6d2
