### ISSUE TITLE
keine OpenWB Daten mehr bei Solax X3

### ISSUE THREAD

**Issue by MagicSven81** [tobiasfaust/SolaxModbusGateway#23]
Hallo Tobias,
leider kommen auch mit dem neuen Update keine OpenWB Daten mehr.
Getestet mit einem Solax X3 Hybrid G4.

Solax X3:
![image](https://github.com/tobiasfaust/SolaxModbusGateway/assets/41968180/ee50c994-19b3-4f79-b2d6-8b1b90ae8278)

Solax X1 oder Solax-MIC scheinen zu funktionieren:
![image](https://github.com/tobiasfaust/SolaxModbusGateway/assets/41968180/a3746e00-8e67-4a65-a1ce-7ed8326fb253)

**Comment by tobiasfaust** [comment]
Mir scheint das dein Update im ESP32 nicht funktioniert hat, 
Steht ganz oben in der Kopfteile auch das neue Datum drin?

**Comment by MagicSven81** [comment]
dummer Fehler meinerseits. Habe die firmware.bin hochgeladen und die neu compilierte heißt firmware(1).bin

Danke, scheint zu funktionieren
