### ISSUE TITLE
ESP WifiManager support no special characters

### ISSUE THREAD

**Issue by MagicSven81** [tobiasfaust/SolaxModbusGateway#28]
Since the last version the ESP WifiManager didn´t support Wlan Passwords with special characters like:

- !
- #

if i change my wlan password to normal alphabetic and numeric charakters everythings works like before.

**Comment by tobiasfaust** [comment]
I‘m using another Wifimanager for Asynchrone Webserver technique.
   https://github.com/alanswx/ESPAsyncWiFiManager

Maybe you can open a Ticket there. It‘s not my responsibility.

**Comment by MagicSven81** [comment]
thx
