### ISSUE TITLE
MQTT IP-Adresse wird abgeschnitten

### ISSUE THREAD

**Issue by Reinhard-M** [tobiasfaust/SolaxModbusGateway#33]
Die via MQTT übertragene IP Adresse wird abgeschnitten wenn alle 4 Felder 3-stellig sind. Die IP-Adresse 192.168.xyz.abc kommt dann als 192.168.xyz.ab an. Wenn ich die IP-Adresse um eine Stelle kürze wird auch die letzte Stelle übertragen. In meinem Beispiel funktionieren also also 192.168.xy.abc oder 192.168.x.abc.

**Comment by tobiasfaust** [comment]
Danke für die Info. 
komme gerade nicht dazu aber werde ich asap prüfen und korrigieren.
