### ISSUE TITLE
Die Daten werden nur im Mqtt Explorere angezeigt

### ISSUE THREAD

**Issue by Bimboboy007** [tobiasfaust/SolaxModbusGateway#36]
Habe das Problem dass die Sensoren beim Deye nur im Mqtt Explorer zu finden sind und nicht in Mqtt als Gerät mit den Sensoren. Muss bei allen Sensoren/Werten ein state_topic erstellen um diese überhaupt zu HA zu bekommen. Wenn dies geschehen ist werden die Werte mal angezeigt mal springen sie auf 0.

**Comment by tobiasfaust** [comment]
Leider habe ich das Problem überhaupt nicht verstanden. Bitte auch Screenshots der weboberfläche vom ESP32 hier anzeigen.

**Comment by Bimboboy007** [comment]
Habe momentan keinen Screenshot. Problembeschreibung wieso taucht das Gerät nicht im MQQTBroker auf ?
Muss die Sensoren mit dem MqttExplorer auslesen und dann jeweils ein state_topic erstellen um die Sensoren in Home Assistant zu haben.
<img width="530" alt="Bildschirmfoto 2023-10-26 um 21 56 43" src="https://github.com/tobiasfaust/SolaxModbusGateway/assets/80967872/00770400-0437-4b52-b327-d4173ad393c9">

**Comment by tobiasfaust** [comment]
Da kann ich nicht helfen, da bist du im HA Forum besser aufgehoben. Wenn die Daten vom ESP32 korrekt alle dem MQTT Broker / Server zugestellt werden ist auf der ESP32 Seite alles in Ordnung

**Comment by Bimboboy007** [comment]
Irgendwie reden wir aneinander vorbei. Genau das macht das Gerät eben nicht die Daten werden an den Mqtt Broker nicht weitergeleitet !  Die Daten sind nur im Mqtt Explorer verfügbar. Das sind 2 verschiedene Sachen.

**Comment by tobiasfaust** [comment]
Was bezeichnet du als MQTT Explorer?
Was hast du als MQTT Server im ESP eingestellt? Screenshot?

**Comment by tobiasfaust** [comment]
Da kann ich mich leider nur wiederholen:
Da die Deye Daten beim MQTT Server korrekt zugestellt werden, das zeigt ja dein MQTT Explorer Screenshot, ist beim ESP32 alles in Ordnung und du musst beim Broker suchen

**Comment by Bimboboy007** [comment]
Das Problem ist das die Sensoren ausser die Messdaten nichts heraus gibt weder eine uniqe_id usw. und deshalb vom Mqtt Broker nicht als solches Gerät erkannt wird.
<img width="370" alt="Bildschirmfoto 2023-11-20 um 19 18 51" src="https://github.com/tobiasfaust/SolaxModbusGateway/assets/80967872/fe57ee70-b9ee-48a2-ae68-61536aa967f1">

**Comment by kommando828** [comment]
No, your broker is not aligned to the data as given out by the ESP, as each Broker needs a different format then you need to break out the message into its parts and then pass only what the broker wants in the format it needs.

I use Node-red to do this on the output from Yasdi2mqtt as this is based on JSON and has all the tools.

**Comment by tobiasfaust** [comment]
Klar, weil im MQTT topic, im Pfad, schon die unique-id drin hängt.

**Comment by Bimboboy007** [comment]
Eine frage habe ich noch. Verkaufen sie das bei keinanzeigen ?

**Comment by tobiasfaust** [comment]
ich habe nochmal nachgesehen, Der MQTT Broker erwartet einen grossen JSON String in dem alle Elemente/MEsswerte gesammelt enthalten sind. Das ist dann wohl ein "Gerät". Immer dasselbe Topic mit einem Json-Datenset.
Das MQTT Gateway arbeitet anders, es sendet alle Messwerte isoliert raus, jeder Messwert für sich. Das hat den vorteil das Apps nur die Messwerte abonieren müssen die sie auch wirklich brauchen.
NAchteil eines JSONS ist auch, das der Json-String wirklich gross werden kann und viel - zu viel- Speicher braucht.

Alternative: die Daten per HTTP-Request holen. Dort wird dann auch ein grosses json array geliefert:

`http://<ip>/getitems`

Um auf die Frage zu antworten: Nein, das verkaufe ich nicht. Das lohnt die Zeit nicht - Die paar Kabel kann jeder selbst zusammen stecken.... ;)

**Comment by tobiasfaust** [comment]
Logisch, hast ja auch die ip vergessen

**Comment by Bimboboy007** [comment]
Hi, also das habe ich schon eingegeben http://<ip>/getitems .
Hab es wieder Gelöscht ist auch nicht so innovativ wie das ESP Projekt, damit kann man auch Änderungen und Einstellungen vornehmen.

**Comment by tobiasfaust** [comment]
Nee, du verstehst es nicht, du musst schon deine richtige IP eintragen, oben im Beispiel ist es nur ein Platzhalter!

**Comment by Bimboboy007** [comment]
Ich hab schon richtig verstanden und das hab ich auch so gemacht. Aber egal für mich hat sich das Project erledigt.
