### ISSUE TITLE
Daten aus Growatt SPH

### ISSUE THREAD

**Issue by HuBeAt** [tobiasfaust/SolaxModbusGateway#37]
Hallo erstmal,:)

Ist es möglich über dieses Gateway auch andere/mehrere Daten aus den WR zu bekommen. Wenn ja wo finde ich die Register Daten.
alle die ich getestet habe stimmen irgendwie nicht mit dem überein was ich angezeigt bekomme.

In der Register.h Datei steht zb bei 'GridFrequency' die Positionen '77, 78'
Und ich bekomme auch die richtigen Werte.
Jedoch finde ich kein Register wo es so dokumentiert wäre.

Sind die Positionen in der Register.h Datei nicht gleich Register?

Mit freundlichen Grüßen

**Comment by tobiasfaust** [comment]
Ja und nein, nicht ganz.
Schau mal ins Wiki wie man die Register aus der Doku umrechnen muss damit es hier passt.

**Comment by HuBeAt** [comment]
Vielen Dank für den schubser 😉
