### ISSUE TITLE
Version 3.1.1 keine RAW Daten

### ISSUE THREAD

**Issue by wwwiesel** [tobiasfaust/SolaxModbusGateway#42]
Hi,

ich bin gerade am versuchen wie ich den Growatt MOD hinbekomme und habe ebenfalls die 3.1.1 genommen, mit dieser bekomme ich keine RAW Life Data angezeigt.

Reproduktion:
Firmware.bin (v3.0) initial installiert... dann im web menü auf update -> neue 3.1.1 firmware aus releases -> keine RAW Life Daten mehr.
Nehme ich wieder die Firmware 3.0 geht wieder alles.

**Comment by tobiasfaust** [comment]
Schau ich mir an, bei mir klappt es nämlich

**Comment by wwwiesel** [comment]
ok, Fehler gefunden, habe eben festgestellt das firmware 3.0 bin immer Daten anzeigt, egal ob angeschlossen oder nicht

**Comment by tobiasfaust** [comment]
Kann sein das fälschlicherweise der debugmode in der 3.0 aktiv war. 
bedeutet, wenn keine Daten kommen wird mit einem teststring gearbeitet. Brauche ich zum entwickeln weil ich nicht immer in der Garage stehen will ;)

die Info das der debugmode und damit der teststring genommen wird steht aber im SerialLog auf der Konsole (wenn du diese auslesen solltest)
