### ISSUE TITLE
Aktuelle v3.1.1 für ESP32-S2 zeigt keine "Item Config" Liste!

### ISSUE THREAD

**Issue by Reinhard-M** [tobiasfaust/SolaxModbusGateway#45]
Ich habe heute mehrfach Binaries mit Gitpod erzeugt. Für v3.1.1 und 3.2.0. Letztere Version ist überhaupt nicht funktionsfähig, v3.1.1 zeigt keine Einstellungen in der "Item Config" Liste:
![Screenshot 2024-02-10 162942](https://github.com/tobiasfaust/SolaxModbusGateway/assets/62464555/adb89bf2-fba1-4f85-88f1-b33bdbb12021)
Außerdem wird in der Konsole folgender Fehler gezeigt:
![Screenshot 2024-02-10 163208](https://github.com/tobiasfaust/SolaxModbusGateway/assets/62464555/bbdcf4e0-7891-41cf-af98-7bd015d630e4)

Ich habe das auf 3 verschiedenen Devices getestet, alle zu Beginn via "ERASE" zurückgesetzt. Eines der 3 Devices hat vorher problemlos funktioniert.

**Comment by tobiasfaust** [comment]
Identisch zu #44
