### ISSUE TITLE
No Support vor Deye Inverters in V3.0

### ISSUE THREAD

**Issue by meisterwinter** [tobiasfaust/SolaxModbusGateway#46]
Dont see any Deye Inverter to select. Is the support for this over?
v3.1 dont get any Values and the Web interface is lighly broken.

**Comment by tobiasfaust** [comment]
name of style.css was wrong, its now fixed

One Deye Inverter is available

**Comment by meisterwinter** [comment]
> name of style.css was wrong, its now fixed
> 
> One Deye Inverter is available

Thanks! 

Is there a compiled release?
