### ISSUE TITLE
Add Solax X3 Ultra Inverter to the list

### ISSUE THREAD

**Issue by qualityrocks** [tobiasfaust/SolaxModbusGateway#50]
Solax X3 Ultra is a new inverter
See attached current modbus protocol
[(Solax)Hybrid X1&X3 IES&ULTRA ModbusTCP&RTU V3.29-English_231012.pdf](https://github.com/tobiasfaust/SolaxModbusGateway/files/14419254/Solax.Hybrid.X1.X3.IES.ULTRA.ModbusTCP.RTU.V3.29-English_231012.pdf)

**Comment by tobiasfaust** [comment]
Sieht sehr ähnlich zum Solax-X3 aus.
Am besten mit der Solax-X3 Einstellung testen und ggf. bei Abweichungen ein neues json erstellen und dann hier posten :)
