### ISSUE TITLE
Initiialisierung Laufvariable

### ISSUE THREAD

**Issue by TigerGrey** [tobiasfaust/SolaxModbusGateway#55]
https://github.com/tobiasfaust/SolaxModbusGateway/blob/4ab4ac707071e295743885177672277a7b631133/src/modbus.cpp#L433C1-L433C41

modbus.cpp
line 433

    for (uint8_t i; i < m.size(); i++) {

sollte da i nicht besser initialisiert werden?

    for (uint8_t i = 0; i < m.size(); i++) {

Tolles Projekt, und das update vorgestern hat es nochmal besser gemacht!

Vielen Dank!

Andreas

**Comment by tobiasfaust** [comment]
Danke für diesen Hinweis, hatte ich tatsächlich übersehen :(
