### ISSUE TITLE
Solax X3 Hybrid G4 issies with 3.2.0

### ISSUE THREAD

**Issue by ingof** [tobiasfaust/SolaxModbusGateway#56]
Hello Tobias,

I created a pull request to add Cell_Voltage_High and Cell_Voltage_Low on my X3 Hybrid.
After building and burning to the ESP32 i have got two issues.

In the RAW-Data there are less values. With 3.1.5 i get over 400 Value (see screenshot in pull request).
But if i want to check now the new values i get 0xundefined instead of the data and get only 322 bytes RAW data.
![Modbus_Gateway_3_2_0](https://github.com/tobiasfaust/SolaxModbusGateway/assets/5514433/09eccdc4-76bf-4e1a-8d16-d6557ae1219c)

But the new data in live view works fine:
![Modbus_Gateway_Values](https://github.com/tobiasfaust/SolaxModbusGateway/assets/5514433/66186d9a-c2f5-4adc-922d-5fe7f9b8f53a)

But there is a problem with "Off Grid Current L1" it shows now randomly strange values and should be zero, because the EPS Mode is not active at the moment.

Did you change the data size of the modbus request in 3.2.0?
Is  it possible to set it in the web interface if i need more raw-data?

**Comment by ingof** [comment]
Ok now i get only 319 bytes of data and it seems it now stable at 319 bytes.

**Comment by tobiasfaust** [comment]
HI Ingo,
if you get "undefined", in the most cases you request more registers than your inverter is able to deliver. Did you change somthing at "RequestLiveData" Item in json?

Its now fine? Can i merge your pullrequest?
