### ISSUE TITLE
Anzeige der Raw Data ist kaputt (seit commits am 11.3.24)

### ISSUE THREAD

**Issue by lattemacchiato** [tobiasfaust/SolaxModbusGateway#60]
Hi,

in der aktuellen Version werden die Raw Data nicht mehr korrekt angezeigt.
Soweit ich das verstehe sollten die (Solax-X3) beginnen mit
ID Data: 0x01 0x03 0x28 ...
Live Data: 0x01 0x04 0xEE ...

Aktuell steht da aber
ID Data: 0x13 0x40 0x72 ...
Live Data: 0x14 0x23 0x88 ...

Ich habe mich mal in den commits "zurückgetastet": Mit dem Codestand vom 29.2. war das noch OK, ab dem Codestand vom 11.3. ist die Raw Data Anzeige offenbar  fehlerhaft. Es fehlen in der "Item Config" auch die on/off Schieber, bzw wurden ersetzt durch Checkboxen.

Sorry wenn ich da falsch hinschaue oder was übersehe....

Paul

**Comment by tobiasfaust** [comment]
Das es checkboxen jetzt (temporär) sind ist normal.
Die RAW Data Anzeige schaue ich mir an

**Comment by TheHexaMaster** [comment]
I can confirm, raw data are corrupted. Any idea what caused this issue for quickfix?

**Comment by TigerGrey** [comment]
Hallo Tobias,
Danke für den Bugfix, suche auch schon einige Zeit an der Stelle rum.
Blöde Frage: Müßte es nicht statt
    if (this->SaveLiveDataframe->at(i) <= 16) {s += "0";}
eher heissen
    if (this->SaveLiveDataframe->at(i) < 16) {s += "0";} ??
Im Prinzip baust Du doch hier eine leading zero ein damit später chunk(...,2) funktioniert, oder?
Für den Fall "=16" wäre aber die erste Stelle im String nicht mehr "0" oder?
Gruß
Andreas

**Comment by TigerGrey** [comment]
noch was ist mir aufgefallen:
Jetzt stimmt zwar die Anzeige der raw data, aber leider funktionieren die "test it" Funktion und auch die Tooltips nur noch bei Zahlen kleiner gleich 9 (also ohne A..F).

**Comment by TigerGrey** [comment]
Vorschlag für rawdata.js:
/*******************************
helper function
*******************************/
function byte2int(bytestring) {
  //return parseInt(Number(bytestring), 16);
  return parseInt(bytestring,16);
}

**Comment by tobiasfaust** [comment]
danke für die Info, ergänze ich noch.

Ich musste das gesamte Frontend umbauen, von serverseitige Generierung auf clientseitige Generierung da bei großem Webcontent der ESP32 beim Erreichen des Speicherlimits die Seite einfach abgeschnitten hat. Gleichzeitig aber so generisch halten, das ich die Basisfunktionalität in meinen anderen Projekten (zb. PumpControl) auch auf einem ESP8266 ebenso einsetzen kann.

Dieser Issue hier sind noch letzte "Nachwehen" ;)

**Comment by lattemacchiato** [comment]
Hi,
Super wie schnell Du reagierst - und ganz herzlichen Dank für die SW und die Arbeit damit!
Paul
