### ISSUE TITLE
Modbus Spec QVolt / Solax-Hybrid G4 v3.29

### ISSUE THREAD

**Issue by lattemacchiato** [tobiasfaust/SolaxModbusGateway#64]
Hi,
ich hätte die aktuelle modbus spec für die G4 von Solax, könnte unter "docs" sinnvoll sein.
[Solax-Hybrid X1&X3-G4 ModbusTCP&RTU V3.29- English.pdf](https://github.com/tobiasfaust/SolaxModbusGateway/files/15129146/Solax-Hybrid.X1.X3-G4.ModbusTCP.RTU.V3.29-.English.pdf)

**Comment by tobiasfaust** [comment]
vielen Dank, vor allem da es die aktuellen Write Register enthält. Habe ich übernommen
