### ISSUE TITLE
esp32 does not boot with connected modbus transceiver

### ISSUE THREAD

**Issue by Gustavw82** [tobiasfaust/SolaxModbusGateway#68]
If iconnect the modbus transceiver (Board HW-97) the esp32 will not boot. if i boot the esp32 and connect the modbus transceiver later it works perfectly. I use esp32-S2 with port pins D16 D17 and D5

**Comment by tobiasfaust** [comment]
Please use other pins, I would start with D5 to change.
Please refer boot pin config in your datasheet

because that, pins are configurable ;)

**Comment by Gustavw82** [comment]
I Connected like in the Picture. but the Issue was still the same. I changed the connection of these three data pins, and connected a capacitor of 47nF between the esp32 and the rs485 transceiver. it seems to work.
