### ISSUE TITLE
Growatt Wechselrichter Modbus Adressen 1000 und 3000

### ISSUE THREAD

**Issue by Gustavw82** [tobiasfaust/SolaxModbusGateway#70]
Hallo. 
Ich habe einf Frage. Ich habe das Projekt jetzt erfolgreich an meinem Wechselrichter (Growatt mod Sph) laufen. Ich habe jetzt seit einiger Zeit einen Akku am Wechselrichter. Die Werte davon würde ich gern auch abfragen.
Leider liegen die Modbus adressen im Bereich größer 1000 bis über 3000.
Wenn ich die Adressen versuche im Testmenü abzurufen bekomme ich nur 0, oder einen Fehler. Ich vermute mal, ich muß dazu in der Configdatei für den Wechselrichter irgendwas anpassen. 
Ich hoffe, es kann mir jemand helfen.

**Comment by tobiasfaust** [comment]
Ja, du musst die config Datei erweitern.
Im Wiki gibt es eine Anleitung dazu.

sobald sie fertig ist würde ich mich freuen wenn du die komplette Datei hier postest damit andere diese auch benutzen können bzw ich sie ins Repo einchecken kann

**Comment by Gustavw82** [comment]
Ich verstehe es leider nicht. Ich bekomme wie gesagt nir 0 oder einen Fehler. Was haben die Einträge bei Request Live Data in der  growatt-sph.json zu bedeuten?

**Comment by tobiasfaust** [comment]
Schau dir mal hier das Attribut „RequestLiveData“ an . Das musst du mit einem weiteren request , nämlich ab Position 1000 ( oder ab der startposittion die du willst bei der Batteriewerte stehen) erweitern. Du kannst immer maximal 0x77 Register mit einer query abfragen.

https://github.com/tobiasfaust/SolaxModbusGateway/wiki/configuration-register

**Comment by Gustavw82** [comment]
Hallo. Also momentan funktioniert es erstmal bei mir. In dem Bereich ab 1000 werden keine Daten ausgegeben. 
![Screenshot_20240718_093608_Firefox](https://github.com/user-attachments/assets/0a0d2a18-b797-4ffe-b988-b5a8542e18b5)

**Comment by tobiasfaust** [comment]
Was heißt denn das es erstmal funktioniert?
Hast du das JSON angepasst? Wenn ja, kannst du die Datei hier posten wenn du final fertig bist?

**Comment by Gustavw82** [comment]
Ich habe mich jetzt näher damit beschäftigt. Man muß die Werte, welche man anzeigen lassen will immer relativ zu dem vorher angegebenen Bereich abfragen. Wenn ich mit dem ersten request von 0-240 einlese, und dem zweiten request ab 3100 dann lautet die richtige Position zum beispiel 3171(State of charge) 388. Das ergibt sich in dem man 71+3 für den header rechnet, dann mal 2, weil es immer 2 stellen sind, und dann plus 240 für die Daten aus dem vorherigen request.
![Screenshot_20240718_091047_Firefox](https://github.com/user-attachments/assets/a3c244a9-c94d-469c-8548-310f1ef45349)
![Screenshot_20240718_091154_Firefox](https://github.com/user-attachments/assets/e24f2693-f977-440f-b91d-d90ecb2c0dd0)
![Screenshot_20240718_091047_Firefox](https://github.com/user-attachments/assets/acde0df4-8a34-4bcb-a16e-b0a19078c710)

**Comment by Gustavw82** [comment]
Ich habe mich jetzt näher damit beschäftigt. Man muß die Werte, welche man anzeigen lassen will immer relativ zu dem vorher angegebenen Bereich abfragen. Wenn ich mit dem ersten request von 0-240 einlese, und dem zweiten request ab 3100 dann lautet die richtige Position zum beispiel 3171(State of charge) 388. Das ergibt sich in dem man 71+3 für den header rechnet, dann mal 2, weil es immer 2 stellen sind, und dann plus 240 für die Daten aus dem vorherigen request.

**Comment by Gustavw82** [comment]
[Growatt-SPH.txt](https://github.com/user-attachments/files/16279695/Growatt-SPH.txt)

**Comment by Gustavw82** [comment]
Die Datei müßte noch in .json umbenannt werden. Ich versuche die nächsten Tage noch mehr Werte einzubauen.

**Comment by tobiasfaust** [comment]
Hast du Einträge angepasst für dich oder nur neue hinzugefügt?
Ich frage deshalb ob ich einen neuen WR-Eintrag machen muss oder die bestehende growatt ersetzen kann.

**Comment by Gustavw82** [comment]
Ein Problem ist noch. Die Seriennummer aus den IDDaten wird nicht korrekt gelesen. Es steht nur unknown. Unter Raw Data steht sie aber korrekt drin.

**Comment by Gustavw82** [comment]
> Hast du Einträge angepasst für dich oder nur neue hinzugefügt? Ich frage deshalb ob ich einen neuen WR-Eintrag machen muss oder die bestehende growatt ersetzen kann.

Ich habe Einträge hinzugefügt, und manche auch angepasst. Für meinen Wechselrichter 
Passt es so. Ob Das für andere auch so ist kann ich nicht sagen.
![Uploading 20240718_100324.jpg…]()

**Comment by tobiasfaust** [comment]
Alles klar, meld dich wenn du fertig bist. Ich würde dann eine neue Sektion für deinen WR anlegen

**Comment by Gustavw82** [comment]
So, Ich bin jetzt erstmal soweit fertig. Ein par Fehlermeldungen konnte ich nicht vernünftig übersetzen, deshalb in englisch. Das einzige, was noch offen wäre, wäre die Anzeige der Seriennummer. Das bekomme ich aber wahrscheinlich nicht selbst hin. Meines erachtens nach ist in der Json-datei alles okay.
[Growatt-SPH.json](https://github.com/user-attachments/files/16289444/Growatt-SPH.json)

**Comment by tobiasfaust** [comment]
Irgendwie passt dein Screenshot oben mit den ID Data nicht zum json. 
im json steht das du 20 Register abfragst (0x14), damit hätte ich 40 ID Einträge in der rawData Seite erwartet. Es sind aber über 100 ;)

Damit ich mir das ansehen kann, kannst du bitte mal  sowohl die Werte von ID-Data als auch LiveData hier als komplette lange Strings posten? Plus bitte den dazugehörigen RawData Screenshot

**Comment by Gustavw82** [comment]
Das kann durchaus sein. Ich hatte einiges probiert.
Hier die richtigen Daten:
IDData:
0x01 0x03 0xEE 0x00 0x01 0x00 0xBD 0xFF 0xFF 0x00
0x64 0x00 0x00 0x27 0x10 0x00 0x00 0x9C 0x40 0x06
0x40 0x44 0x4E 0x31 0x2E 0x30 0x00 0x5A 0x42 0x44
0x42 0x00 0x02 0x00 0x02 0x00 0x00 0x06 0x40 0x00
0x3C 0x00 0x3C 0x00 0x5A 0x00 0x5A 0x00 0x00 0x00
0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00
0x00 0x00 0x00 0x00 0x01 0x00 0x64 0x00 0x00 0x00
0x00 0x20 0x20 0x20 0x50 0x56 0x20 0x49 0x6E 0x76
0x65 0x72 0x74 0x65 0x72 0x20 0x20 0x00 0x00 0x15
0x18 0x02 0x03 0x07 0xE8 0x00 0x07 0x00 0x13 0x00
0x08 0x00 0x10 0x00 0x05 0x00 0x05 0x0C 0x73 0x13
0x73 0x12 0x8E 0x14 0x1E 0x07 0x00 0x13 0x73 0x12
0x8E 0x14 0x1E 0x07 0x00 0x13 0x73 0x12 0x8E 0x14
0x1E 0x0D 0x61 0x10 0xF6 0x12 0x9D 0x13 0x8D 0x00
0x98 0x00 0x32 0x00 0x32 0x00 0x32 0x00 0x32 0x00
0x32 0x00 0x32 0x00 0x32 0x00 0x32 0x00 0x32 0x00
0x32 0x00 0x32 0x11 0x1E 0x00 0x00 0x44 0x4E 0x41
0x41 0x30 0x31 0x35 0x31 0x30 0x30 0x30 0x32 0x01
0x31 0x00 0x00 0x00 0x00 0x13 0x9C 0x00 0x32 0x10
0x07 0x10 0xA6 0x0F 0x18 0x0E 0x79 0x00 0x14 0x00
0x05 0x10 0x57 0x0F 0x90 0x26 0xFD 0x26 0xFD 0x26
0xA5 0x27 0xC1 0x27 0xC1 0x28 0x21 0x00 0x0A 0x00
0x00 0x01 0xE4 0x00 0xFF 0x4E 0x20 0x00 0xFF 0x4E
0x20 0x00 0xFF 0x4E 0x20 0x00 0xFF 0x4E 0x20 0x07
0x00 0xFC 0xE5

LiveData:
00x01 0x04 0xEE 0x00 0x01 0x00 0x00 0x32 0x8F 0x07
0xF5 0x00 0x00 0x00 0x00 0x00 0x00 0x0B 0xC2 0x00
0x2B 0x00 0x00 0x32 0x8F 0x00 0x00 0x00 0x00 0x00
0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00
0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00
0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00
0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00
0x00 0x00 0x00 0x00 0x00 0x05 0xED 0x13 0x86 0x09
0x5B 0x00 0x06 0x00 0x00 0x05 0x9D 0x09 0x5C 0x00
0x06 0x00 0x00 0x05 0x9D 0x09 0x4D 0x00 0x06 0x00
0x00 0x05 0x94 0x10 0x54 0x10 0x1B 0x10 0x1B 0x00
0x00 0x00 0x03 0x00 0x00 0x5F 0x9F 0x01 0xA8 0xF8
0x7A 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00
0x00 0x00 0x0B 0x00 0x00 0x67 0x99 0x00 0x00 0x00
0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00
0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00
0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00
0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00
0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x67 0x99 0x01
0xBD 0x01 0x63 0x01 0x54 0x00 0x00 0x01 0x79 0x0C
0xD4 0x0C 0xCA 0x4E 0x20 0x00 0x00 0x00 0x00 0x9C
0x40 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00
0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00
0x03 0x00 0x3C 0x00 0x00 0x00 0x00 0x00 0x00 0x00
0x00 0x07 0xFA 0x01 0x04 0xEE 0x4E 0x20 0x00 0x03
0x00 0x00 0x9C 0x40 0x00 0x00 0x00 0x00 0x00 0x00
0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00
0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x3C 0x00 0x00
0x00 0x00 0x00 0x01 0x00 0x00 0x00 0x00 0x00 0x00
0x0A 0x25 0x00 0x00 0x00 0x05 0x00 0x00 0x00 0x02
0x00 0x00 0x20 0x19 0x00 0x00 0x00 0x08 0x00 0x00
0x21 0xD5 0x00 0x00 0x00 0x02 0x00 0x00 0x00 0x51
0x00 0x00 0x66 0xD9 0x00 0x00 0x00 0x05 0x00 0x00
0x50 0x16 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00
0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00
0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00
0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x27 0x10
0x00 0x00 0x19 0xA0 0x00 0x00 0x00 0x00 0x01 0x01
0x00 0x00 0x00 0x00 0x53 0x00 0x00 0x30 0x00 0x12
0x19 0x9E 0x0D 0x4A 0x00 0x15 0x00 0x15 0x01 0x61
0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x28 0x14
0x00 0x00 0x20 0x19 0x00 0x00 0x21 0xD5 0x00 0x00
0x00 0x03 0x0C 0x54 0x00 0x39 0x00 0x10 0x00 0x00
0x01 0x01 0x00 0xE1 0x00 0x02 0x00 0x10 0x00 0x00
0x00 0x00 0x00 0x01 0x00 0x00 0x00 0x31 0x00 0x31
0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00
0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00
0x00 0x01 0x00 0x00 0x00 0x00 0x00 0x12 0x52 0x94
0x01 0xCC 0x01 0xA5 0xD1 0x6FxEE 0x00 0x01 0x00 0x00 0x32 0x8F 0x07
0xF5 0x00 0x00 0x00 0x00 0x00 0x00 0x0B 0xC2 0x00
0x2B 0x00 0x00 0x32 0x8F 0x00 0x00 0x00 0x00 0x00
0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00
0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00
0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00
0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00
0x00 0x00 0x00 0x00 0x00 0x05 0xED 0x13 0x86 0x09
0x5B 0x00 0x06 0x00 0x00 0x05 0x9D 0x09 0x5C 0x00
0x06 0x00 0x00 0x05 0x9D 0x09 0x4D 0x00 0x06 0x00
0x00 0x05 0x94 0x10 0x54 0x10 0x1B 0x10 0x1B 0x00
0x00 0x00 0x03 0x00 0x00 0x5F 0x9F 0x01 0xA8 0xF8
0x7A 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00
0x00 0x00 0x0B 0x00 0x00 0x67 0x99 0x00 0x00 0x00
0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00
0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00
0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00
0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00
0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x67 0x99 0x01
0xBD 0x01 0x63 0x01 0x54 0x00 0x00 0x01 0x79 0x0C
0xD4 0x0C 0xCA 0x4E 0x20 0x00 0x00 0x00 0x00 0x9C
0x40 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00
0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00
0x03 0x00 0x3C 0x00 0x00 0x00 0x00 0x00 0x00 0x00
0x00 0x07 0xFA 0x01 0x04 0xEE 0x4E 0x20 0x00 0x03
0x00 0x00 0x9C 0x40 0x00 0x00 0x00 0x00 0x00 0x00
0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00
0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x3C 0x00 0x00
0x00 0x00 0x00 0x01 0x00 0x00 0x00 0x00 0x00 0x00
0x0A 0x25 0x00 0x00 0x00 0x05 0x00 0x00 0x00 0x02
0x00 0x00 0x20 0x19 0x00 0x00 0x00 0x08 0x00 0x00
0x21 0xD5 0x00 0x00 0x00 0x02 0x00 0x00 0x00 0x51
0x00 0x00 0x66 0xD9 0x00 0x00 0x00 0x05 0x00 0x00
0x50 0x16 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00
0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00
0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00
0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x27 0x10
0x00 0x00 0x19 0xA0 0x00 0x00 0x00 0x00 0x01 0x01
0x00 0x00 0x00 0x00 0x53 0x00 0x00 0x30 0x00 0x12
0x19 0x9E 0x0D 0x4A 0x00 0x15 0x00 0x15 0x01 0x61
0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x28 0x14
0x00 0x00 0x20 0x19 0x00 0x00 0x21 0xD5 0x00 0x00
0x00 0x03 0x0C 0x54 0x00 0x39 0x00 0x10 0x00 0x00
0x01 0x01 0x00 0xE1 0x00 0x02 0x00 0x10 0x00 0x00
0x00 0x00 0x00 0x01 0x00 0x00 0x00 0x31 0x00 0x31
0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00
0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00
0x00 0x01 0x00 0x00 0x00 0x00 0x00 0x12 0x52 0x94
0x01 0xCC 0x01 0xA5 0xD1 0x6F

**Comment by Gustavw82** [comment]
> Irgendwie passt dein Screenshot oben mit den ID Data nicht zum json. im json steht das du 20 Register abfragst (0x14), damit hätte ich 40 ID Einträge in der rawData Seite erwartet. Es sind aber über 100 ;)
> 
> Damit ich mir das ansehen kann, kannst du bitte mal sowohl die Werte von ID-Data als auch LiveData hier als komplette lange Strings posten? Plus bitte den dazugehörigen RawData Screenshot

Benötigst Du noch weitere Informationen?

**Comment by Gustavw82** [comment]
Hallo, und Guten Morgen. 
Es gibt neue Erkenntnisse. 
Die Seriennummer steht bei meinem Wechselrichter ab der position 209. Sie ist 10 Stellen lang. Ich lese die IdDaten ab 0x78. Die richtige Stelle ist dann 181, bis 190.
Was mir aufgefallen ist, wenn man bei den IDDaten mehrere Bereiche angibt, so wie bei den Livedaten, dann wird unter Rawdata nichts mehr angezeigt. Nur mal so als info.
Ich hänge mal meine aktuelle Json Datei hier an.

{
  "Growatt-SPH": {
    "config": {
      "RequestLiveData": [
        [
          "#ClientID",
          "0x04",
          "0x00",
          "0x00",
          "0x00",
          "0x77"
        ],
        [
          "#ClientID",
          "0x04",
          "0x0C",
          "0x1C",
          "0x00",
          "0x77"
        ]
      ],
      "RequestIdData": [
        "#ClientID",
        "0x03",
        "0x00",
        "0x78",
        "0x00",
        "0x77"
      ],
      "ClientIdPos": 0,
      "LiveDataFunctionCodePos": 1,
      "LiveDataFunctionCode": "0x04",
      "IdDataFunctionCodePos": 1,
      "IdDataFunctionCode": "0x03",
      "LiveDataStartsAtPos": 3,
      "IdDataStartsAtPos": 3,
      "LiveDataErrorPos": 1,
      "LiveDataErrorCode": "0x84",
      "IdDataErrorPos": 1,
      "IdDataErrorCode": "0x83",
      "LiveDataSuccessPos": 1,
      "LiveDataSuccessCode": "0x04",
      "IdDataSuccessPos": 1,
      "IdDataSuccessCode": "0x03"
    },
    "data": {
      "livedata": [
        {
          "position": [
            3,
            4
          ],
          "name": "InverterRunState",
          "realname": "Inverter Status",
          "datatype": "integer",
          "mapping": [
            [
              0,
              "WaitMode"
            ],
            [
              1,
              "NormalMode"
            ],
            [
              3,
              "FaultMode"
            ]
          ]
        },
        {
          "position": [
            5,
            6,
            7,
            8
          ],
          "name": "InputPower",
          "realname": "Erzeugungsleistung Gesamt",
          "openwbtopic": "openWB/set/pv/W",
          "datatype": "float",
          "factor": 0.1,
          "unit": "W"
        },
        {
          "position": [
            13,
            14,
            15,
            16
          ],
          "name": "PowerPv1",
          "realname": "Erzeugungsleistung Pv1",
          "openwbtopic": "openWB/set/pv/1/W",
          "datatype": "float",
          "factor": 0.1,
          "unit": "W"
        },
        {
          "position": [
            17,
            18
          ],
          "name": "Spannung PV2",
          "realname": "Spannung PV2",
          "datatype": "float",
          "factor": 0.1,
          "unit": "V"
        },
        {
          "position": [
            19,
            20
          ],
          "name": "Strom PV2",
          "realname": "Strom PV2",
          "datatype": "float",
          "factor": 0.1,
          "unit": "A"
        },
        {
          "position": [
            21,
            22,
            23,
            24
          ],
          "name": "PowerPv2",
          "realname": "Erzeugungsleistung Pv2",
          "openwbtopic": "openWB/set/pv/2/W",
          "datatype": "float",
          "factor": 0.1,
          "unit": "W"
        },
        {
          "position": [
            73,
            74,
            75,
            76
          ],
          "name": "Output Power",
          "realname": "Ausgangsleistung",
          "datatype": "float",
          "factor": 0.1,
          "unit": "W"
        },
        {
          "position": [
            77,
            78
          ],
          "name": "GridFrequency",
          "realname": "Netzfrequenz",
          "datatype": "float",
          "factor": 0.01,
          "unit": "Hz"
        },
        {
          "position": [
            79,
            80
          ],
          "name": "SpannungL1",
          "realname": "Spannung L1",
          "datatype": "float",
          "factor": 0.1,
          "unit": "V"
        },
        {
          "position": [
            81,
            82
          ],
          "name": "Strom L1",
          "realname": "Strom L1",
          "datatype": "float",
          "factor": 0.1,
          "unit": "A"
        },
        {
          "position": [
            83,
            84,
            85,
            86
          ],
          "name": "Leistung L1",
          "realname": "Leistung L1",
          "datatype": "float",
          "factor": 0.1,
          "unit": "VA"
        },
        {
          "position": [
            87,
            88
          ],
          "name": "SpannungL2",
          "realname": "Spannung L2",
          "datatype": "float",
          "factor": 0.1,
          "unit": "V"
        },
        {
          "position": [
            89,
            90
          ],
          "name": "Strom L2",
          "realname": "Strom L2",
          "datatype": "float",
          "factor": 0.1,
          "unit": "A"
        },
        {
          "position": [
            91,
            92,
            93,
            94
          ],
          "name": "Leistung L2",
          "realname": "Leistung L2",
          "datatype": "float",
          "factor": 0.1,
          "unit": "VA"
        },
        {
          "position": [
            95,
            96
          ],
          "name": "SpannungL3",
          "realname": "Spannung L3",
          "datatype": "float",
          "factor": 0.1,
          "unit": "V"
        },
        {
          "position": [
            97,
            98
          ],
          "name": "Strom L3",
          "realname": "Strom L3",
          "datatype": "float",
          "factor": 0.1,
          "unit": "A"
        },
        {
          "position": [
            99,
            100,
            101,
            102
          ],
          "name": "Leistung L3",
          "realname": "Leistung L3",
          "datatype": "float",
          "factor": 0.1,
          "unit": "VA"
        },
        {
          "position": [
            103,
            104
          ],
          "name": "SpannungL1L2",
          "realname": "Spannung L1 L2",
          "datatype": "float",
          "factor": 0.1,
          "unit": "V"
        },
        {
          "position": [
            105,
            106
          ],
          "name": "SpannungL2L3",
          "realname": "Spannung L2 L3",
          "datatype": "float",
          "factor": 0.1,
          "unit": "V"
        },
        {
          "position": [
            107,
            108
          ],
          "name": "SpannungL3L1",
          "realname": "Spannung L3 L1",
          "datatype": "float",
          "factor": 0.1,
          "unit": "V"
        },
        {
          "position": [
            109,
            110,
            111,
            112
          ],
          "name": "Energy generated today",
          "realname": "Erzeugte Energie heute",
          "datatype": "integer",
          "factor": 0.1,
          "unit": "KWh"
        },
        {
          "position": [
            113,
            114,
            115,
            116
          ],
          "name": "Total Energy generated",
          "realname": "Erzeugte Energie Gesamt",
          "datatype": "integer",
          "factor": 0.1,
          "unit": "KWh"
        },
        {
          "position": [
            117,
            118,
            119,
            120
          ],
          "name": "Worktime total",
          "realname": "Arbeitszeit Gesamt",
          "datatype": "integer",
          "factor": 0.5,
          "unit": "s"
        },
        {
          "position": [
            121,
            122,
            123,
            124
          ],
          "name": "TodayEnergyKWhPv1",
          "realname": "Erzeugte Energie Pv1 heute",
          "openwbtopic": "openWB/set/pv/1/WhCounter",
          "datatype": "integer",
          "factor": 0.1,
          "unit": "KWh"
        },
        {
          "position": [
            125,
            126,
            127,
            128
          ],
          "name": "TotalEnergyWhPv1",
          "realname": "Erzeugte Energie Pv1 in Wh",
          "openwbtopic": "openWB/set/pv/1/WhCounter",
          "datatype": "integer",
          "factor": 100,
          "unit": "Wh"
        },
        {
          "position": [
            129,
            130,
            131,
            132
          ],
          "name": "TodayEnergyKWhPv2",
          "realname": "Erzeugte Energie Pv2 heute",
          "openwbtopic": "openWB/set/pv/2/WhCounter",
          "datatype": "integer",
          "factor": 0.1,
          "unit": "KWh"
        },
        {
          "position": [
            133,
            134,
            135,
            136
          ],
          "name": "TotalEnergyWhPv2",
          "realname": "Erzeugte Energie Pv2 in Wh",
          "openwbtopic": "openWB/set/pv/2/WhCounter",
          "datatype": "integer",
          "factor": 100,
          "unit": "Wh"
        },
        {
          "position": [
            133,
            134,
            135,
            136
          ],
          "name": "TotalEnergyKwhPv2",
          "realname": "Erzeugte Energie Pv2 in Kwh",
          "openwbtopic": "openWB/set/pv/2/WhCounter",
          "datatype": "float",
          "factor": 0.1,
          "unit": "KWh"
        },
        {
          "position": [
            189,
            190
          ],
          "name": "InverterTemperature",
          "realname": "Inverter Temperatur",
          "datatype": "float",
          "factor": 0.1,
          "unit": "°C"
        },
        {
          "position": [
            384,
            385
          ],
          "name": "BatVoltage",
          "realname": "Battery Voltage",
          "datatype": "float",
          "factor": 0.01,
          "unit": "V"
        },
        {
          "position": [
            408,
            409
          ],
          "name": "BatChargingPower",
          "realname": "Battery Charging Power",
          "openwbtopic": "openWB/set/houseBattery/W",
          "datatype": "float",
          "factor": 0.1,
          "unit": "W"
        },
        {
          "position": [
            213,
            214
          ],
          "name": "Faultcode",
          "realname": "Inverter Fehlercode",
          "datatype": "integer"
        },
        {
          "position": [
            213,
            214
          ],
          "name": "Faultmessage",
          "realname": "Inverter Fehlermeldung",
          "datatype": "integer",
          "mapping": [
            [
              0,
              "Kein Fehler"
            ],
            [
              1,
              "Fehler:99+X"
            ],
            [
              2,
              "Fehler:99+X"
            ],
            [
              3,
              "Fehler:99+X"
            ],
            [
              4,
              "Fehler:99+X"
            ],
            [
              5,
              "Fehler:99+X"
            ],
            [
              6,
              "Fehler:99+X"
            ],
            [
              7,
              "Fehler:99+X"
            ],
            [
              8,
              "Fehler:99+X"
            ],
            [
              9,
              "Fehler:99+X"
            ],
            [
              10,
              "Fehler:99+X"
            ],
            [
              11,
              "Fehler:99+X"
            ],
            [
              12,
              "Fehler:99+X"
            ],
            [
              13,
              "Fehler:99+X"
            ],
            [
              14,
              "Fehler:99+X"
            ],
            [
              15,
              "Fehler:99+X"
            ],
            [
              16,
              "Fehler:99+X"
            ],
            [
              17,
              "Fehler:99+X"
            ],
            [
              18,
              "Fehler:99+X"
            ],
            [
              19,
              "Fehler:99+X"
            ],
            [
              20,
              "Fehler:99+X"
            ],
            [
              21,
              "Fehler:99+X"
            ],
            [
              22,
              "Fehler:99+X"
            ],
            [
              23,
              "Fehler:99+X"
            ],
            [
              24,
              "Auto Test fehlgeschlagen"
            ],
            [
              25,
              "Keine Netzverbindung"
            ],
            [
              26,
              "PV Isolation schlecht"
            ],
            [
              27,
              "Residual I High"
            ],
            [
              28,
              "Output High DCI"
            ],
            [
              29,
              "PV Spannung Hoch"
            ],
            [
              30,
              "Netzspannung außer Toleranz"
            ],
            [
              31,
              "Netzfrequenz außer Toleranz"
            ],
            [
              32,
              "Temperatur zu hoch"
            ]
          ]
        },
        {
          "position": [
            305,
            306
          ],
          "name": "PAC to Grid",
          "realname": "Leistung AC ins Netz",
          "datatype": "integer",
          "unit": "Kwh"
        },
        {
          "position": [
            388,
            389
          ],
          "name": "BatCapacity",
          "realname": "Battery Capacity (SOC)",
          "openwbtopic": "openWB/set/houseBattery/%Soc",
          "datatype": "integer",
          "unit": "%"
        },
        {
          "position": [
            414,
            415,
            416,
            417
          ],
          "name": "InputEnergyChargeWh",
          "realname": "Geladene Energie Speicher (Wh)",
          "openwbtopic": "openWB/set/houseBattery/WhImported",
          "datatype": "integer",
          "factor": 100,
          "unit": "Wh"
        },
        {
          "position": [
            414,
            415,
            416,
            417
          ],
          "name": "InputEnergyChargeKwh",
          "realname": "Geladene Energie Speicher (KWh)",
          "datatype": "float",
          "factor": 0.1,
          "unit": "KWh"
        },
        {
          "position": [
            410,
            411,
            412,
            413
          ],
          "name": "OutputEnergyChargeWh",
          "realname": "Entladene Energie Speicher (Wh)",
          "openwbtopic": "openWB/set/houseBattery/WhExported",
          "datatype": "integer",
          "factor": 100,
          "unit": "Wh"
        },
        {
          "position": [
            410,
            411,
            412,
            413
          ],
          "name": "OutputEnergyChargeKwh",
          "realname": "Entladene Energie Speicher (KWh)",
          "datatype": "float",
          "factor": 0.1,
          "unit": "KWh"
        },
        {
          "position": [
            571,
            572,
            573,
            574
          ],
          "name": "Energiebezug Netz gesamt",
          "realname": "Energiebezug Netz (KWh)",
          "datatype": "float",
          "factor": 0.1,
          "unit": "KWh"
        },
        {
          "position": [
            575,
            576,
            577,
            578
          ],
          "name": "Einspeisung Netz gesamt",
          "realname": "Einspeisung Netz (KWh)",
          "datatype": "float",
          "factor": 0.1,
          "unit": "KWh"
        }
      ],
      "id": [
        {
          "position": [
            181,
            182,
            183,
            184,
            185,
            186,
            187,
            188,
            189,
            190
          ],
          "name": "InverterSN",
          "realname": "Inverter SerialNumber",
          "datatype": "string"
        }
      ]
    }
  }
}
