### ISSUE TITLE
Function "device reboot" does not work probably

### ISSUE THREAD

**Issue by MagicSven81** [tobiasfaust/SolaxModbusGateway#79]
Beim Ausführen der Funktion "device reboot" lädt er das Modul in einem iFrame anstatt es in der MainPage zu laden.

Siehe Screenshot:

![image](https://github.com/user-attachments/assets/3e039369-5719-4d71-9458-3fedc61b9fbc)

**Comment by tobiasfaust** [comment]
Sollte eigentlich im aktuellen Code nicht mehr so sein….. ist das der aktuelle github stand?

**Comment by MagicSven81** [comment]
Mit dem aktuellen Update wurde dieser Bug behoben

**Comment by MagicSven81** [comment]
Seit der Version 3.2.3 ist der Fehler wieder vorhanden.

Siehe Video:

https://streamable.com/z14044

**Comment by tobiasfaust** [comment]
sorry, geht wieder
ddab0931e1325709e3d39ddd221b0bfa34540822
