### ISSUE TITLE
CRC Check and data lenght check can´t be disabled

### ISSUE THREAD

**Issue by MagicSven81** [tobiasfaust/SolaxModbusGateway#83]
beide CRC Checks lassen sich zwar im Menü deaktivieren und speichern,
aber nachdem die Seite neu geladen wird sind diese wieder aktiviert.

Auch ist es dann leider nicht mehr möglich einzelne Register über das littlefs Filesystem zu editieren und zu testen,
da durch den CRC Check immer wieder die original Datei geladen wird.

**Comment by tobiasfaust** [comment]
Passt es jetzt?

**Comment by MagicSven81** [comment]
Leider nein.
Ich hab hier mal ein kurzes Video gemacht, worum es genau geht.

https://streamable.com/vl9enx

**Comment by tobiasfaust** [comment]
Das ist der Browser Cache. Es ist eigentlich nicht vorgesehen das die html Dateien geändert werden. Falls du doch Änderungen machst, bitte lösche einmal den Browser Cache nach der Änderung

**Comment by MagicSven81** [comment]
it works - thx
