### ISSUE TITLE
Firmware Update?

### ISSUE THREAD

**Issue by ronk74** [tobiasfaust/SolaxModbusGateway#85]
Hallo,

bei mir läuft noch FW3.1.1. Ich möchte den ESP32 gern auf die aktuelle Firmware updaten. Reicht es aus, die Firmware über das Webinterface hochzuladen? Oder muss der Weg über das Flash Download Tool gegangen werden? Weiterhin weiß ich nicht genau, welche ESP32-Version ich habe, ist das irgendwo zu erkennen?

Vielen Dank!

**Comment by MagicSven81** [comment]
hier musst du über das Flash Download Tool gehen, da du auch die littlefs.bin hochladen musst.
Vermutlich hast du einen ESP32 (normal) - wichtig, die Settings wie von Tobias im Wiki geschrieben verwenden.

**Comment by ronk74** [comment]
Danke sehr. Ich probiere das morgen. Viele Grüße!

**Comment by ronk74** [comment]
Update ist geglückt. Danke für die Hilfe!
