### ISSUE TITLE
Add Documentation for Firmware update

### ISSUE THREAD

**Issue by lassediercks** [tobiasfaust/SolaxModbusGateway#86]
Hey there, first of all: thank you. 

I've bought a deye gateway labeled device with a 3d printed case on ebay and its running this software.
It's connected to a deye sun 12k and eveyrthing works as expected.

I know enough to setup the gateway & modbus and make use of the data.
I don't know enough to figure out which file from the [releases](https://github.com/tobiasfaust/SolaxModbusGateway/releases/tag/v.3.2.2--10662716707) I should upload 

to fix that issue for potentially everyone, could there be a little section on how to update the firmware? 

again: thank you!

**Comment by tobiasfaust** [comment]
Hi,
Is this page not sufficient?

https://github.com/tobiasfaust/SolaxModbusGateway/wiki/build-with-gitpod

**Comment by lassediercks** [comment]
yeah I guess if you know the architecture of you device :D 

thank you
