### ISSUE TITLE
modbus item configuration -- Only the first 26 objects can be selected

### ISSUE THREAD

**Issue by steffenk1981** [tobiasfaust/SolaxModbusGateway#9]
Hi, 
can you please check the code for the following problem. 
Only the first 26 items can be selected. All others are not saved. 
If you want to send a value further down via MQTT, this does not work.

I can also provide my register.h for SolaX / Q.Home. In it, all values up to item 480 are currently displayed correctly.

Best regards

**Comment by tobiasfaust** [comment]
Hi,
Thanks for your Report. Did you See any error Message at usb serial Monitor while saving your config?

**Comment by steffenk1981** [comment]
Hi,
Thank you very much for the quick implementation. Works perfectly
