### ISSUE TITLE
Gateway forgets Item Config with every restart

### ISSUE THREAD

**Issue by benhubert** [tobiasfaust/SolaxModbusGateway#90]
First of all, thanks for your work and this great project!

Here's the issue with my gateway:
Every time I power cycle my gateway all Items are unchecked again (except for one). I have to walk through all items and tick the checkbox to receive updates again. All other configuration (Basis Config, Modbus Config) is restored after reboot.

My Inverter: Solax X3 G4
Inverter Type in use: Solax-X3
Release in use: 3.2.3 (`@development`) of Oct 8 2024 22:15:16

If you need any other information, let me know.

**Comment by tobiasfaust** [comment]
Hi,
sorry, but i cannot reproduce your incident. I tested on a fresh ESP32, select Solax-X3, checked some items, store it and reboot. After reboot all items are still checked. Please see the log.

You can check with files section the file "modbusitemconfig.json" if all your checked items are stored sucessfully. 

<pre>
ets Jun  8 2016 00:22:57

rst:0x10 (RTCWDT_RTC_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:2
load:0x3fff0030,len:1184
load:0x40078000,len:13232
load:0x40080400,len:3028
entry 0x400805e4
Start of Solar Inverter MQTT Gateway
Starting BaseConfig
[    65][E][vfs_api.cpp:105] open(): /littlefs/baseconfig.json does not exist, no permits for creation

ready
Starting Wifi and MQTT
WiFi Start
WiFi interface ready
WiFi client started
Connected to access point
WiFi connected with local IP: 10.0.2.102
Starting MQTT (test.mosquitto.org:1883)
[  5365][E][vfs_api.cpp:105] open(): /littlefs/modbusconfig.json does not exist, no permits for creation
[  9558][E][vfs_api.cpp:105] open(): /littlefs/modbusitemconfig.json does not exist, no permits for creation
MQTT aktiviert
Starting WebServer
WebServer started...
Attempting MQTT connection as Solax-48071
connected... 
reading config file
opened config file
{
  "data": {
    "mqttroot": "Solax",
    "SelectConnectivity": "wifi",
    "mqttserver": "test.mosquitto.org",
    "mqttport": "1883",
    "mqttbasepath": "home",
    "UseRandomClientID": "yes",
    "serial_rx": 3,
    "serial_tx": 1,
    "sel_auth": "off",
    "debuglevel": 3
  }
}Request queue data to inverter: 0x01 0x03 0x01 0xF4 0x00 0x77 0x45 0xE2 
Read Data from Queue: 
no response from client
Request queue data to inverter: 0x01 0x03 0x02 0x6B 0x00 0x41 0xF5 0x9E 
Read Data from Queue: 
no response from client
Request queue data to inverter: 0x01 0x03 0x01 0xF4 0x00 0x77 0x45 0xE2 
Read Data from Queue: 
no response from client
Request queue data to inverter: 0x01 0x03 0x02 0x6B 0x00 0x41 0xF5 0x9E 
Read Data from Queue: 
no response from client
Request queue data to inverter: 0x01 0x03 0x01 0xF4 0x00 0x77 0x45 0xE2 
Read Data from Queue: 
no response from client
Request queue data to inverter: 0x01 0x03 0x02 0x6B 0x00 0x41 0xF5 0x9E 
Read Data from Queue: 
no response from client
Request queue data to inverter: 0x01 0x03 0x01 0xF4 0x00 0x77 0x45 0xE2 
Read Data from Queue: 
no response from client
Upload Complete: /modbusconfig.json ,size: 245 Bytes
reading config file....
config file is open:
{
  "data": {
    "pin_rx": 16,
    "pin_tx": 17,
    "pin_rts": 5,
    "clientid": "1",
    "baudrate": 19200,
    "txintervallive": 5,
    "txintervalid": 3600,
    "invertertype": "Solax-X3",
    "EnableRelays": "0",
    "enable_openwbtopic": 0,
    "enableCrcCheck": 1,
    "enableLengthCheck": 1,
    "enable_setters": 0
  }
}
Invertertyp 'Solax-X3' was found in register file 'Solax-X3.json', set it as selected active Inverter
Start Hardwareserial 1 on RX (16), TX(17), RTS(5)
Init Modbus to Client 0x01 with 19200 Baud
open register file from Filesystem: Deye_SUN_SG04LP3.json
Inverter found: Deye SUN-xx-SG04LP3
Request queue data to inverter: 0x01 0x03 0x02 0x6B 0x00 0x41 0xF5 0x9E 
open register file from Filesystem: GoodWe.json
Inverter found: Goodwe
Read Data from Queue:
no response from client
open register file from Filesystem: Growatt-MOD.json
Inverter found: Growatt-MOD_4000_TL3-XH
open register file from Filesystem: Growatt-SPH.json
Inverter found: Growatt-SPH
open register file from Filesystem: QVolt.json
Inverter found: QVolt-HYP-G3-3P
open register file from Filesystem: Sofar.json
Inverter found: Sofar-KTL Solarmax-SGA
open register file from Filesystem: Solax-MIC-Pro.json
Inverter found: Solax-Mic-Pro
open register file from Filesystem: Solax-MIC.json
Inverter found: Solax-Mic
open register file from Filesystem: Solax-X1.json
Inverter found: Solax-X1
open register file from Filesystem: Solax-X3.json
Inverter found: Solax-X3
Inverter found: Solax-X3-PRO
[ 89937][E][vfs_api.cpp:105] open(): /littlefs/modbusitemconfig.json does not exist, no permits for creation
modbusitemconfig.json config File not exists, all items are inactive as default
Request queue data to inverter: 0xFF 0xFF 
Read Data from Queue: 
no response from client
Request queue data to inverter: 0xFF 0xFF 
Read Data from Queue: 
no response from client
Request queue data to inverter: 0xFF 0xFF 
Read Data from Queue: 
no response from client
Request queue data to inverter: 0xFF 0xFF 
Read Data from Queue: 
no response from client
Request queue data to inverter: 0xFF 0xFF 
Read Data from Queue: 
no response from client
Request queue data to inverter: 0x01 0x04 0x00 0x00 0x00 0x78 0xF0 0x28 
Read Data from Queue: 
no response from client
Request queue data to inverter: 0x01 0x04 0x00 0x78 0x00 0x77 0x30 0x35 
Read Data from Queue: 
no response from client
Request queue data to inverter: 0x01 0x04 0x00 0x00 0x00 0x78 0xF0 0x28 
Read Data from Queue: 
no response from client
Request queue data to inverter: 0x01 0x04 0x00 0x78 0x00 0x77 0x30 0x35 
Read Data from Queue: 
no response from client
Request queue data to inverter: 0x01 0x04 0x00 0x00 0x00 0x78 0xF0 0x28 
Read Data from Queue: 
no response from client
Request queue data to inverter: 0x01 0x04 0x00 0x78 0x00 0x77 0x30 0x35 
Read Data from Queue: 
no response from client
Request queue data to inverter: 0x01 0x04 0x00 0x00 0x00 0x78 0xF0 0x28 
Read Data from Queue: 
no response from client
Request queue data to inverter: 0x01 0x04 0x00 0x78 0x00 0x77 0x30 0x35 
Read Data from Queue: 
no response from client
Set Item <GridVoltage_R> ActiveState to true
Set Item <GridCurrent_R> ActiveState to true
Set Item <GridPower_R> ActiveState to true
Request queue data to inverter: 0x01 0x04 0x00 0x00 0x00 0x78 0xF0 0x28 
Read Data from Queue: 
no response from client
Request queue data to inverter: 0x01 0x04 0x00 0x78 0x00 0x77 0x30 0x35 
Read Data from Queue: 
no response from client
Set Item <GridFrequency_R> ActiveState to true
Request queue data to inverter: 0x01 0x04 0x00 0x00 0x00 0x78 0xF0 0x28 
Read Data from Queue: 
no response from client
Set Item <PvVoltage1> ActiveState to true
Request queue data to inverter: 0x01 0x04 0x00 0x78 0x00 0x77 0x30 0x35 
Read Data from Queue: 
no response from client
Set Item <PvCurrent1> ActiveState to true
Set Item <PowerPv1> ActiveState to true
Request queue data to inverter: 0x01 0x04 0x00 0x00 0x00 0x78 0xF0 0x28 
Read Data from Queue: 
no response from client
Set Item <BatPower> ActiveState to true
Request queue data to inverter: 0x01 0x04 0x00 0x78 0x00 0x77 0x30 0x35 
Read Data from Queue: 
no response from client
Set Item <GridStatus> ActiveState to true
Request queue data to inverter: 0x01 0x04 0x00 0x00 0x00 0x78 0xF0 0x28 
Read Data from Queue: 
no response from client
Request queue data to inverter: 0x01 0x04 0x00 0x78 0x00 0x77 0x30 0x35 
Read Data from Queue: 
no response from client
Upload Complete: /modbusitemconfig.json ,size: 1345 Bytes
reading modbus item config file....
modbus item config file is open:
item GridVoltage_R -> enabled
item GridCurrent_R -> enabled
item GridPower_R -> enabled
item GridFrequency_R -> enabled
item GridVoltage_S -> disabled
item GridCurrent_S -> disabled
item GridPower_S -> disabled
item GridFrequency_S -> disabled
item GridVoltage_T -> disabled
item GridCurrent_T -> disabled
item GridPower_T -> disabled
item GridFrequency_T -> disabled
item PvVoltage1 -> enabled
item PvVoltage2 -> disabled
item PvCurrent1 -> enabled
item PvCurrent2 -> disabled
item Temperature -> disabled
item InverterStatus -> disabled
item PowerPv1 -> enabled
item PowerPv2 -> disabled
item BatVoltage -> disabled
item BatCurrent -> disabled
item BatPower -> enabled
item BatTemp -> disabled
item GridStatus -> enabled
item BatCapacity -> disabled
item OutputEnergyChargeWh -> disabled
item OutputEnergyChargeKWh -> disabled
item OutputEnergyChargeToday -> disabled
item InputEnergyChargeWh -> disabled
item InputEnergyChargeKWh -> disabled
item InputEnergyChargeToday -> disabled
item feedinPower -> disabled
item feedinEnergyTotal -> disabled
item consumedEnergyTotal -> disabled
item EnergyTodayToGrid -> disabled
item EnergyTotalToGridKwh -> disabled
item EnergyTotalToGridWh -> disabled
item OnGridRunTime -> disabled
item OffGridRunTime -> disabled
item OffGridVoltage_R -> disabled
item OffGridCurrent_R -> disabled
item OffGridPowerActive_R -> disabled
item OffGridVoltage_S -> disabled
item OffGridCurrent_S -> disabled
item OffGridPowerActive_S -> disabled
item OffGridVoltage_T -> disabled
item OffGridCurrent_T -> disabled
item OffGridPowerActive_T -> disabled
item FeedInPowerPhase_R -> disabled
item FeedInPowerPhase_S -> disabled
item FeedInPowerPhase_T -> disabled
item OffGridYieldTotal -> disabled
item OffGridYieldToday -> disabled
item EChargeToday -> disabled
item EChargeTotal -> disabled
item SolarEnergyTotal -> disabled
item SolarEnergyToday -> disabled
item EnergyFeedin -> disabled
item EnergyConsum -> disabled
item CellVoltageHigh -> disabled
item CellVoltageLow -> disabled
Request queue data to inverter: 0x01 0x04 0x00 0x00 0x00 0x78 0xF0 0x28 
Read Data from Queue: 
no response from client
Request queue data to inverter: 0x01 0x04 0x00 0x78 0x00 0x77 0x30 0x35 
Read Data from Queue: 
no response from client
Request queue data to inverter: 0x01 0x04 0x00 0x00 0x00 0x78 0xF0 0x28 
Read Data from Queue: 
no response from client
Request queue data to inverter: 0x01 0x04 0x00 0x78 0x00 0x77 0x30 0x35 
Read Data from Queue: 
no response from client
Request queue data to inverter: 0x01 0x04 0x00 0x00 0x00 0x78 0xF0 0x28 
Read Data from Queue: 
no response from client
Request queue data to inverter: 0x01 0x04 0x00 0x78 0x00 0x77 0x30 0x35 
Read Data from Queue: 
no response from client
Request queue data to inverter: 0x01 0x04 0x00 0x00 0x00 0x78 0xF0 0x28 
Read Data from Queue: 
no response from client
Request queue data to inverter: 0x01 0x04 0x00 0x78 0x00 0x77 0x30 0x35 
Read Data from Queue: 
no response from client
Request queue data to inverter: 0x01 0x04 0x00 0x00 0x00 0x78 0xF0 0x28 
Read Data from Queue: 
no response from client
Request queue data to inverter: 0x01 0x04 0x00 0x78 0x00 0x77 0x30 0x35 
Read Data from Queue: 
no response from client
Request queue data to inverter: 0x01 0x04 0x00 0x00 0x00 0x78 0xF0 0x28
Read Data from Queue:
no response from client
Request queue data to inverter: 0x01 0x04 0x00 0x78 0x00 0x77 0x30 0x35
Read Data from Queue:
no response from client
Request to Reboot, wait 5sek ...
Request queue data to inverter: 0x01 0x04 0x00 0x00 0x00 0x78 0xF0 0x28
Read Data from Queue:
no response from client
Request queue data to inverter: 0x01 0x04 0x00 0x78 0x00 0x77 0x30 0x35
Read Data from Queue:
no response from client
Rebooting...
Disconnected from WiFi access point
WiFi clients stopped
ets Jun  8 2016 00:22:57

rst:0xc (SW_CPU_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:2
load:0x3fff0030,len:1184
load:0x40078000,len:13232
load:0x40080400,len:3028
entry 0x400805e4        
ets Jun  8 2016 00:22:57

rst:0x10 (RTCWDT_RTC_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:2
load:0x3fff0030,len:1184
load:0x40078000,len:13232
load:0x40080400,len:3028
entry 0x400805e4
Start of Solar Inverter MQTT Gateway
Starting BaseConfig
reading config file
opened config file
{
  "data": {
    "mqttroot": "Solax",
    "SelectConnectivity": "wifi",
    "mqttserver": "test.mosquitto.org",
    "mqttport": "1883",
    "mqttbasepath": "home",
    "UseRandomClientID": "yes",
    "serial_rx": 3,
    "serial_tx": 1,
    "sel_auth": "off",
    "debuglevel": 3
  }
}
ready
Starting Wifi and MQTT
Go into Wifi Mode
WiFi Start
WiFi interface ready
WiFi client started
Connected to access point
WiFi connected with local IP: 10.0.2.102
Starting MQTT (test.mosquitto.org:1883)
open register file from Filesystem: Deye_SUN_SG04LP3.json
Inverter found: Deye SUN-xx-SG04LP3
open register file from Filesystem: GoodWe.json
Inverter found: Goodwe
open register file from Filesystem: Growatt-MOD.json
Inverter found: Growatt-MOD_4000_TL3-XH
open register file from Filesystem: Growatt-SPH.json
Inverter found: Growatt-SPH
open register file from Filesystem: QVolt.json
Inverter found: QVolt-HYP-G3-3P
open register file from Filesystem: Sofar.json
Inverter found: Sofar-KTL Solarmax-SGA
open register file from Filesystem: Solax-MIC-Pro.json
Inverter found: Solax-Mic-Pro
open register file from Filesystem: Solax-MIC.json
Inverter found: Solax-Mic
open register file from Filesystem: Solax-X1.json
Inverter found: Solax-X1
open register file from Filesystem: Solax-X3.json
Inverter found: Solax-X3
Inverter found: Solax-X3-PRO
reading config file....
config file is open:
{
  "data": {
    "pin_rx": 16,
    "pin_tx": 17,
    "pin_rts": 5,
    "clientid": "1",
    "baudrate": 19200,
    "txintervallive": 5,
    "txintervalid": 3600,
    "invertertype": "Solax-X3",
    "EnableRelays": "0",
    "enable_openwbtopic": 0,
    "enableCrcCheck": 1,
    "enableLengthCheck": 1,
    "enable_setters": 0
  }
}
Invertertyp 'Solax-X3' was found in register file 'Solax-X3.json', set it as selected active Inverter
Start Hardwareserial 1 on RX (16), TX(17), RTS(5)
Init Modbus to Client 0x01 with 19200 Baud
open register file from Filesystem: Deye_SUN_SG04LP3.json
Inverter found: Deye SUN-xx-SG04LP3
open register file from Filesystem: GoodWe.json
Inverter found: Goodwe
open register file from Filesystem: Growatt-MOD.json
Inverter found: Growatt-MOD_4000_TL3-XH
open register file from Filesystem: Growatt-SPH.json
Inverter found: Growatt-SPH
open register file from Filesystem: QVolt.json
Inverter found: QVolt-HYP-G3-3P
open register file from Filesystem: Sofar.json
Inverter found: Sofar-KTL Solarmax-SGA
open register file from Filesystem: Solax-MIC-Pro.json
Inverter found: Solax-Mic-Pro
open register file from Filesystem: Solax-MIC.json
Inverter found: Solax-Mic
open register file from Filesystem: Solax-X1.json
Inverter found: Solax-X1
open register file from Filesystem: Solax-X3.json
Inverter found: Solax-X3
Inverter found: Solax-X3-PRO
reading modbus item config file....
modbus item config file is open:
item GridVoltage_R -> enabled
item GridCurrent_R -> enabled
item GridPower_R -> enabled
item GridFrequency_R -> enabled
item GridVoltage_S -> disabled
item GridCurrent_S -> disabled
item GridPower_S -> disabled
item GridFrequency_S -> disabled
item GridVoltage_T -> disabled
item GridCurrent_T -> disabled
item GridPower_T -> disabled
item GridFrequency_T -> disabled
item PvVoltage1 -> enabled
item PvVoltage2 -> disabled
item PvCurrent1 -> enabled
item PvCurrent2 -> disabled
item Temperature -> disabled
item InverterStatus -> disabled
item PowerPv1 -> enabled
item PowerPv2 -> disabled
item BatVoltage -> disabled
item BatCurrent -> disabled
item BatPower -> enabled
item BatTemp -> disabled
item GridStatus -> enabled
item BatCapacity -> disabled
item OutputEnergyChargeWh -> disabled
item OutputEnergyChargeKWh -> disabled
item OutputEnergyChargeToday -> disabled
item InputEnergyChargeWh -> disabled
item InputEnergyChargeKWh -> disabled
item InputEnergyChargeToday -> disabled
item feedinPower -> disabled
item feedinEnergyTotal -> disabled
item consumedEnergyTotal -> disabled
item EnergyTodayToGrid -> disabled
item EnergyTotalToGridKwh -> disabled
item EnergyTotalToGridWh -> disabled
item OnGridRunTime -> disabled
item OffGridRunTime -> disabled
item OffGridVoltage_R -> disabled
item OffGridCurrent_R -> disabled
item OffGridPowerActive_R -> disabled
item OffGridVoltage_S -> disabled
item OffGridCurrent_S -> disabled
item OffGridPowerActive_S -> disabled
item OffGridVoltage_T -> disabled
item OffGridCurrent_T -> disabled
item OffGridPowerActive_T -> disabled
item FeedInPowerPhase_R -> disabled
item FeedInPowerPhase_S -> disabled
item FeedInPowerPhase_T -> disabled
item OffGridYieldTotal -> disabled
item OffGridYieldToday -> disabled
item EChargeToday -> disabled
item EChargeTotal -> disabled
item SolarEnergyTotal -> disabled
item SolarEnergyToday -> disabled
item EnergyFeedin -> disabled
item EnergyConsum -> disabled
item CellVoltageHigh -> disabled
item CellVoltageLow -> disabled
MQTT aktiviert
Failed to parse JSON Register <set> Data: EmptyInput
Starting WebServer
WebServer started...
Request queue data to inverter: 0xFF 0xFF 
Read Data from Queue: 
no response from client
Request queue data to inverter: 0xFF 0xFF 
Read Data from Queue: 
no response from client
Attempting MQTT connection as Solax-17258
connected... 
Publish home/Solax/IP: 10.0.2.102
Publish home/Solax/version: 3.2.3(@development)
Publish home/Solax/state: Online
Request queue data to inverter: 0xFF 0xFF 
Read Data from Queue: 
no response from client
Request queue data to inverter: 0xFF 0xFF 
Read Data from Queue: 
no response from client
Request queue data to inverter: 0xFF 0xFF 
Read Data from Queue: 
no response from client
Request queue data to inverter: 0x01 0x04 0x00 0x00 0x00 0x78 0xF0 0x28 
Read Data from Queue: 
no response from client
</pre>

**Comment by MagicSven81** [comment]
sorry for my stupid question, but did you "save" the settings after you activate the items?

**Comment by tobiasfaust** [comment]
Yes, of course. Save Button does Save it.

**Comment by benhubert** [comment]
Absolutely not a stupid question! :tada: It is very likely that I never saw this save button before. Now, also after a reboot, all my items are activated again. Many thanks @MagicSven81 !

But I have to add ... this button is quite far away from the table and it only appears when I scroll down to the very bottom. This could be improved from UX perspective:
![image](https://github.com/user-attachments/assets/0b8673a9-e6e0-486b-ad2f-9806553bc940)
